import { expect, test } from '@playwright/test'

test('Approval Request gallery previews every state and exports Adaptive Card JSON', async ({ context, page }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'], { origin: 'http://127.0.0.1:4173' })
  await page.goto('/?preview=approval-notification')

  await expect(page.getByRole('heading', { name: 'Approval Request notification', level: 1 })).toBeVisible()
  await expect(page.getByRole('button', { name: /Pending Approval/ })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: /Already Actioned \/ Stale/ })).toBeVisible()
  const pendingPreview = page.getByTitle('Pending Approval desktop email preview').contentFrame()
  await expect(pendingPreview.getByRole('img', { name: 'Houston Independent School District' })).toBeVisible()
  await expect(pendingPreview.getByText('Action required', { exact: true })).toBeVisible()
  await expect(pendingPreview.getByRole('heading', { name: 'A field trip needs your approval' })).toBeVisible()
  await expect(pendingPreview.getByRole('link', { name: /Open full request in Experience Pass/ })).toBeVisible()
  await expect(pendingPreview.getByRole('link', { name: 'Request Details' })).toBeVisible()
  await expect(pendingPreview.getByRole('button', { name: 'Approve' })).toBeVisible()
  await expect(pendingPreview.getByRole('button', { name: 'Reject' })).toBeVisible()
  const detailsBox = await pendingPreview.getByRole('link', { name: 'Request Details' }).boundingBox()
  const approveBox = await pendingPreview.getByRole('button', { name: 'Approve' }).boundingBox()
  const rejectBox = await pendingPreview.getByRole('button', { name: 'Reject' }).boundingBox()
  expect(await pendingPreview.getByRole('button', { name: 'Approve' }).evaluate((button) => getComputedStyle(button).backgroundColor)).toBe('rgb(0, 163, 175)')
  expect(await pendingPreview.getByRole('button', { name: 'Approve' }).evaluate((button) => getComputedStyle(button).color)).toBe('rgb(255, 255, 255)')
  expect(await pendingPreview.getByRole('link', { name: 'Request Details' }).evaluate((link) => getComputedStyle(link).backgroundColor)).toBe('rgb(255, 255, 255)')
  expect(await pendingPreview.getByRole('link', { name: 'Request Details' }).evaluate((link) => getComputedStyle(link).borderRadius)).toBe('8px')
  expect(detailsBox!.height).toBe(approveBox!.height)
  expect(approveBox!.height).toBe(rejectBox!.height)

  await page.getByRole('button', { name: /Pending · Additional Review/ }).click()
  await expect(page.getByTitle('Pending · Additional Review desktop email preview').contentFrame().getByText('Additional Review Required')).toBeVisible()

  await page.getByRole('button', { name: /^03 Pending · Title I\b/ }).click()
  const titleIPreview = page.getByTitle('Pending · Title I desktop email preview').contentFrame()
  await expect(titleIPreview.getByText('Title I coordination')).toBeVisible()
  await expect(titleIPreview.getByText(/Title I will be reaching out on a separate timeline/)).toBeVisible()
  await expect(titleIPreview.getByText('Transportation Services coordination')).toHaveCount(0)

  await page.getByRole('button', { name: /^04 Pending · Title I \+ HISD Bus\b/ }).click()
  const titleIHisdBusPreview = page.getByTitle('Pending · Title I + HISD Bus desktop email preview').contentFrame()
  await expect(titleIHisdBusPreview.getByText('Title I coordination')).toBeVisible()
  await expect(titleIHisdBusPreview.getByText('Transportation Services coordination', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: /Reject Confirmation/ }).click()
  const rejectPreview = page.getByTitle('Reject Confirmation desktop email preview').contentFrame()
  await expect(rejectPreview.getByRole('button', { name: 'Confirm Reject' })).toBeVisible()
  await expect(rejectPreview.getByRole('button', { name: 'Cancel' })).toBeVisible()
  await expect(rejectPreview.getByRole('textbox')).toHaveCount(0)
  await expect(rejectPreview.getByRole('link', { name: 'View Request' })).toHaveCount(0)
  await expect(page.getByLabel('Generated Adaptive Card JSON')).toContainText('"version": "1.0"')
  await expect(page.getByLabel('Generated Adaptive Card JSON')).not.toContainText('"type": "Input.Text"')

  await page.getByRole('button', { name: /Approved/ }).click()
  const approvedPreview = page.getByTitle('Approved desktop email preview').contentFrame()
  const viewRequest = approvedPreview.getByRole('link', { name: 'View Request' })
  await expect(viewRequest).toBeVisible()
  await expect(approvedPreview.getByRole('heading', { name: 'Request FTR-1042 has been approved' })).toBeVisible()
  await expect(approvedPreview.getByText('Dr. Jordan Lee')).toBeVisible()
  await expect(approvedPreview.getByText('Morgan Davis')).toBeVisible()
  await expect(approvedPreview.getByText('Taylor Brooks')).toBeVisible()
  await expect(approvedPreview.getByText('August 18, 2026')).toBeVisible()
  await expect(approvedPreview.getByText('Houston Museum of Natural Science')).toBeVisible()
  await expect(approvedPreview.getByText(/No contact timeline is currently available/)).toBeVisible()
  expect(await viewRequest.evaluate((link) => getComputedStyle(link).width)).not.toBe('auto')

  await page.getByRole('button', { name: /^08 Rejected/ }).click()
  const rejectedPreview = page.getByTitle('Rejected desktop email preview').contentFrame()
  await expect(rejectedPreview.getByText('August 18, 2026')).toBeVisible()
  await expect(rejectedPreview.getByText('Houston Museum of Natural Science')).toBeVisible()

  await page.getByRole('button', { name: /Submitted Receipt/ }).click()
  const submittedPreview = page.getByTitle('Submitted Receipt desktop email preview').contentFrame()
  await expect(submittedPreview.getByRole('heading', { name: 'Your request has been submitted' })).toBeVisible()
  await expect(submittedPreview.getByText(/Please await completion of the approval process/)).toBeVisible()
  await expect(submittedPreview.getByText('August 18, 2026')).toBeVisible()
  await expect(submittedPreview.getByText('Houston Museum of Natural Science')).toBeVisible()
  await expect(submittedPreview.getByText('Dr. Jordan Lee')).toBeVisible()
  await expect(submittedPreview.getByText('Morgan Davis')).toBeVisible()
  await expect(submittedPreview.getByText('Taylor Brooks')).toBeVisible()
  await expect(submittedPreview.getByText(/No contact timeline is currently available/)).toBeVisible()

  await page.getByRole('button', { name: 'Copy Adaptive Card JSON' }).click()
  await expect(page.getByText('Adaptive Card JSON copied.')).toBeVisible()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('"version": "1.0"')

  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download JSON' }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('approval-request-submitted.adaptive-card.json')
  await expect(page.getByText('Downloaded approval-request-submitted.adaptive-card.json.')).toBeVisible()
})

test('Approval Request gallery remains usable at a representative narrow width', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/?preview=approval-notification')

  await expect(page.getByRole('heading', { name: 'Approval Request notification', level: 1 })).toBeVisible()
  await expect(page.getByRole('button', { name: /Pending · Title I \+ HISD Bus/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /^Error$/ })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Copy Adaptive Card JSON' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
